In [1]:
import numpy as np

In [2]:
# cria uma matriz unidimensional
mt = np.array([12, 34, 26, 18, 10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [5]:
# cria o array com um tipo específico
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#mudar o tipo do array
#podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.9999])
print(mtnew)
#quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4     3.6    -5.1     9.42    4.9999]
[ 1  3 -5  9  4]


In [7]:
# podemos fazer o inverso também
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [8]:
#mais de uma dimensão
#cria uma matriz bidimensional
mt7 = np.array([[7, 2, 23], [12, 27, 4],[5, 34, 23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [11]:
#cria arrays vazios tipificados
#empty significa que não inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("--------")
# cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("--------")
# com valores igual a um
um = np.ones([5,7])
print(um)
print("--------")
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[140671709191456 140671709191456]
 [              0               0]
 [              0               0]]
--------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
--------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("--------------------")
#valores aleatórios distribuidos normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("--------------------")
#valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)
print("--------------------")

[0.58760852 0.47029429 0.11299907 0.15001865 0.34973904]
--------------------
[ 0.88576403 -0.2376132  -1.25020974  0.03310916 -1.34210829]
--------------------
[[6.44425774 6.31442609 6.97797157 9.35710968]
 [6.40311735 2.18259224 1.21480973 8.46150292]
 [2.66455516 6.18127711 1.49939279 9.2674815 ]]
--------------------


In [18]:
#outra forma de gerar aleatórios
#uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [19]:
#unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [20]:
#funções específicas
# cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# Mostra a matriz k
print(k)
# Mostra um elemento específico da matriz k
print(k[0][1])
# Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [21]:
#Funções Matemáticas
# Mostra o maior valor da matriz k
print(k.max())
# Mostra o menor valor da matriz k
print(k.min())
# Mostra a soma dos valores da matriz k
print((k.sum()))
# Mostra o valor da média dos valores da matriz k
print(k.mean())
# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [22]:
#funções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [23]:
#extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
# Mostra o elemento da posição 2
print(m[1])
print("-------")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-------")
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])
print("-------")
# Mostra o array criado a partir da antepenúltima
#posição até o final
print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [24]:
#extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("-------")
#primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("-------")
#segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("-------")
#terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print("-------")
#todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("-------")
#todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]


In [25]:
#adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)
print("-------")
res2 = n*o
print(res2)
print("-------")
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [26]:
# transposição, rearranja um conjunto de 15 elementos de 0 a 14 
# em 3 linhas e 5 colunas.
f = np.arange(15).reshape((3, 5))
# mostra a matrizes transposta entre linha e coluna
print(f)
print("-------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [27]:
#outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3, 5))
print(r)
print("-------")
# rearranja um conjunto de 15 elementos 
# mostra a matrizes transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [28]:
#expressões lógicas
#usando where
# criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
# criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
# criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[-1.15054802  0.39013399 -1.08291233 -1.60427561]
 [ 0.18337342  1.21145369 -2.23116607 -0.2791458 ]
 [ 1.05464038  0.0132399  -1.35025729  1.7550169 ]
 [-2.34393604  0.24908791  0.04884817  1.025043  ]]
[[False  True False False]
 [ True  True False False]
 [ True  True False  True]
 [False  True  True  True]]
[[-1  1 -1 -1]
 [ 1  1 -1 -1]
 [ 1  1 -1  1]
 [-1  1  1  1]]
